version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - "${DB_PORT}:3306"
    container_name: my-mysql-container
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
